apiVersion: v1
kind: Service
metadata:
  name: nfl
  namespace: game-2048
  labels:
    app: nfl
spec:
  selector:
    app: nfl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort